# fly.toml app configuration file generated for dk-reminders-bot on 2025-11-24T13:40:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dk-reminders-bot'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080   # или что у тебя там
  force_https = true

  # важно:
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  DB_PATH = "/data/reminders.db"

[[mounts]]
  source = "reminders_data"
  destination = "/data"